[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
runner = "onmcu run --board NUCLEO-WL55JC --file"
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "info"
